version: "3.8"

services:
  yt-dlp-server:
    image: ${IMAGE_NAME}
    container_name: yt-dlp-server
    restart: unless-stopped
    ports:
      - 8080

    environment:
      YT_DLP_SERVER_HOST: "0.0.0.0"
      YT_DLP_SERVER_PORT: "8080"
      DEFAULT_AUDIO_FORMAT: "mp3"
      DEFAULT_AUDIO_QUALITY: "best"
      MAX_CONCURRENT_DOWNLOADS: "3"
      MAX_FILE_AGE_HOURS: "6"
      CLEANUP_INTERVAL_SECONDS: "600"
      MIN_FREE_DISK_MB: "100"
      LOG_LEVEL: "INFO"
      TZ: "${TZ:-UTC}"
      DOMAIN: "${DOMAIN}"

    # Expose only through Traefik (no direct host port publish)
    networks:
      - dokploy-network

    volumes:
      - ./downloads:/app/downloads

    env_file:
      - path: .env

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s

    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.1"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.services.yt-dlp-server.loadbalancer.server.port=8080"

      # HTTPS router
      - "traefik.http.routers.yt-dlp-server.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.yt-dlp-server.entrypoints=websecure"
      - "traefik.http.routers.yt-dlp-server.tls.certresolver=letsencrypt"

      # HTTP -> HTTPS redirect router
      - "traefik.http.routers.yt-dlp-server-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.yt-dlp-server-web.entrypoints=web"
      - "traefik.http.routers.yt-dlp-server-web.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

volumes:
  downloads_temp:
    driver: local

networks:
  dokploy-network:
    external: true